application: appspot-oauth-handler
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cleanup
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest
- name: pycrypto
  version: latest
